/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as GoodMorningImagesRouteImport } from './routes/good-morning-images'
import { Route as RenderIdRouteImport } from './routes/render.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const GoodMorningImagesRoute = GoodMorningImagesRouteImport.update({
  id: '/good-morning-images',
  path: '/good-morning-images',
  getParentRoute: () => rootRouteImport,
} as any)
const RenderIdRoute = RenderIdRouteImport.update({
  id: '/render/$id',
  path: '/render/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/good-morning-images': typeof GoodMorningImagesRoute
  '/render/$id': typeof RenderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/good-morning-images': typeof GoodMorningImagesRoute
  '/render/$id': typeof RenderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/good-morning-images': typeof GoodMorningImagesRoute
  '/render/$id': typeof RenderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$' | '/good-morning-images' | '/render/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$' | '/good-morning-images' | '/render/$id'
  id: '__root__' | '/' | '/$' | '/good-morning-images' | '/render/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  GoodMorningImagesRoute: typeof GoodMorningImagesRoute
  RenderIdRoute: typeof RenderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/good-morning-images': {
      id: '/good-morning-images'
      path: '/good-morning-images'
      fullPath: '/good-morning-images'
      preLoaderRoute: typeof GoodMorningImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/render/$id': {
      id: '/render/$id'
      path: '/render/$id'
      fullPath: '/render/$id'
      preLoaderRoute: typeof RenderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  GoodMorningImagesRoute: GoodMorningImagesRoute,
  RenderIdRoute: RenderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
